baseURL               = "https://navibox.org/"
languageCode          = "zh-CN"
title                 = "NaviBox - 专业的AI导航平台 | 人工智能工具一站式导航"
theme                 = "navibox"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录
assetsDir             = "assets"                    # 静态资源目录
assetsPath            = "/assets/"                  # 静态资源路径


[params]
    author        = "我的名字"
    description   = "NaviBox是专业的人工智能工具导航平台，收录优质AI对话、AI图像、AI视频、AI写作、AI办公与AI编程工具，助您快速发现和使用前沿AI应用"
    keywords      = "AI导航,人工智能工具,AI对话,AI图像,AI视频,AI写作,AI编程,AI办公"
    upload        = "https://www.yuque.com/forms/share/1a1fee15-f7a9-4ee6-9dd4-b0ba9fef1871"      # 左侧导航栏的"网站提交"
    about         = "https://github.com/shenweiyan/Knowledge-Garden/discussions/10"	          # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "Navibox 你的AI导航站"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务
    fancybox      = true                                        # 使用 Fancybox 实现图片灯箱/放大功能

[params.seo]    
    baiduhmid       = ''	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 
    googleAnalytics = ''                    # Google Analytics ID
    baiduPush       = true                  # 百度自动推送

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/ai-favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-bio.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/ai-expand-dark.png"
    logoExpandDark    = "assets/images/ai-expand-light.png"
    logoCollapseLight = "assets/images/ai.png"
    logoCollapseDark  = "assets/images/ai.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：navibox.163.com <br/>'
